function [z2d_res, z2d_fit, params, params_ci]=fit_convex_hyperbolic_cylinder_height(x2d, y2d, z2d, pqtxy, is_opt)
% fit_convex_hyperbolic_cylinder_height provide a convenient way to fit parameters
% from a measured convex hyperbolic cylinder height.


[z2d_res, z2d_fit, params, params_ci] = optimize_parameters ...
    ( @generate_2d_cylinder_height ...
    , @standard_convex_hyperbolic_cylinder_height ...
    , x2d, y2d, z2d, pqtxy, is_opt);